name: CI
on:
  push:
    branches: [ v3-and-v4 ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON_BLACK: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

